[package]
name = "protobuf-gen"
version = "0.2.0"
authors = ["Boncheol Gu <boncheol.gu@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
failure = "0.1"
heck = "0.3"
log = "0.4"
prost = "0.5"
prost-build = "0.5"
protobuf-gen-derive = { path = "protobuf-gen-derive" }
protobuf-gen-extract = { path = "protobuf-gen-extract" }
syn = { version = "0.15", features = ["full"] }
syn_util = "0.3"

[dev-dependencies]
env_logger = "0.6"
